### ISSUE TITLE
Newsfeed API Process

### ISSUE THREAD

**Issue by bryanj4** [jeffbernst/creative-crypto#26]
You say in the main README.md that all you need to do is change the username of the account you want to use and it should work. I noticed that you need to include the creative-crypto-api in the newsfeed function in `src/actions/index.js`. 

What do you need to do on the server end to get it to work? I think it has something to do with the JWT authentication.

**Comment by bryanj4** [comment]
`[jacobbryan@localhost creative-crypto-api]$ npm start

> creative-crypto-api@1.0.0 start /home/jacobbryan/code/creative-crypto-api
> node server.js

/home/jacobbryan/code/creative-crypto-api/node_modules/passport-jwt/lib/strategy.js:45
        throw new TypeError('JwtStrategy requires a secret or key');
        ^

TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (/home/jacobbryan/code/creative-crypto-api/node_modules/passport-jwt/lib/strategy.js:45:15)
    at Object.<anonymous> (/home/jacobbryan/code/creative-crypto-api/strategies.js:6:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jacobbryan/code/creative-crypto-api/routes/usersRouter.js:16:38)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! creative-crypto-api@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the creative-crypto-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jacobbryan/.npm/_logs/2018-05-26T18_04_08_038Z-debug.log
`

**Comment by bryanj4** [comment]
Never mind. The issue isn't here.

**Comment by jeffbernst** [comment]
Actually all of the newsfeed stuff is from a previous build that used a custom twitter feed. I need to delete all of that stuff to avoid confusing people. Glad you got it to work!
